import time
from selenium import webdriver
driver = webdriver.Chrome('D:\ki2nam3\KiemThuPhanMem\Chrome_Driver\chromedriver.exe')
driver.maximize_window()
driver.get('http://practice.automationtesting.in/')
next1 = driver.find_element_by_xpath('//*[@id="menu-item-50"]/a')
next1.click()
email_reg = driver.find_element_by_id('reg_email')
email_reg.send_keys('a123@gmail.com')
pass_reg = driver.find_element_by_id('reg_password')
pass_reg.send_keys('123abc')
btn_reg = driver.find_element_by_name('register')
btn_reg.submit()
time.sleep(2)
driver.quit()